backend:
  name: git-gateway
  branch: master
local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "story"
    label: "Stories"
    folder: "content/story"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "story" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Story-image", name: "storyImage", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"} ] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "audio1"
    label: "Audio1"
    folder: "content/audio1"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "audio1" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Audio image", name: "image", widget: "image" }
      - { label: "Short description", name: "shortDescription", widget: "string" }
      - { label: "Full description", name: "fullDescription", widget: "markdown" }

  - name: "training1"
    label: "Training1"
    folder: "content/training1"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "training1" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Training image", name: "image", widget: "image" }
      - { label: "Short description", name: "shortDescription", widget: "string" }
      - { label: "Full description", name: "fullDescription", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/index.md"
        label: "Homepage"
        name: "index"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page" }
          - { label: "Headline-Left", name: "headlineLeft", widget: "string" }
          - { label: "Featured entries", name: "featuredEntries", widget: "list", hint: "Select 6 entries from audio/training/stories", types:
            [
            {
              label: "Audio",
              name: "audio",
              widget: "object",
              fields:
                [
                {
                  label: "Audio",
                  name: "items",
                  widget: "relation",
                  collection: "audio1",
                  file: "audio1",
                  valueField: "title",
                  searchFields: ["title"],
                  displayFields: ["title"],
                  multiple: true,
                  required: false,
                }
                ]
            },
            {
              label: "Training",
              name: "training",
              widget: "object",
              fields:
                [
                {
                  label: "Training",
                  name: "items",
                  widget: "relation",
                  collection: "training1",
                  file: "training1",
                  valueField: "title",
                  searchFields: ["title"],
                  displayFields: ["title"],
                  multiple: true,
                  required: false,
                }
                ]
            },
            {
              label: "Story",
              name: "story",
              widget: "object",
              fields:
                [
                {
                  label: "Story",
                  name: "items",
                  widget: "relation",
                  collection: "story",
                  file: "story",
                  valueField: "title",
                  searchFields: ["title"],
                  displayFields: ["title"],
                  multiple: true,
                  required: false,
                }
                ]
            }
            ] }
          - { label: "Footer", name: "footer", widget: "object", fields: [{label: "Column-1", name: "column1", widget: "object", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }]}, {label: "Column-2", name: "column2", widget: "object", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }]}, {label: "Column-3", name: "column3", widget: "object", fields: [{ label: "Title", name: "title", widget: "string" }, { label: "Body", name: "body", widget: "markdown" }]}] }
      - file: "content/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main-image", name: "mainImage", widget: "object", fields: [{label: "Image", name: "image", widget: "image"}, {label: "Alt", name: "alt", widget: "string"}] }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/training/index.md"
        label: "Training"
        name: "training"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "training" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/audio/index.md"
        label: "Audio"
        name: "audio"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "audio" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Audio List", name: "audioList", widget: "list", fields: [{label: "Small image", name: "smallImage", widget: "object", fields: [{label: "Add to homepage (Up to 6 entries possible)", name: "featuredEntry", widget: "boolean", required: false}, {label: "Title", name: "title", widget: "string"}, {label: "Image", name: "image", widget: "image"}, {label: "Link", name: "link", widget: "string"}]}, {label: "Large image", name: "largeImage", widget: "object", fields: [{label: "Add to homepage (Up to 6 entries possible)", name: "featuredEntry", widget: "boolean", required: false}, {label: "Title", name: "title", widget: "string"}, {label: "Image", name: "image", widget: "image"}, {label: "Link", name: "link", widget: "string"}]}] }
