name: Checks

on: [push]

jobs:
  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: gatsby serve -p 8000
          wait-on: http://localhost:8000
